"""Abstract storage protocols."""

from __future__ import annotations

from typing import Protocol

from hippocampus.models.memory import Memory, MemoryCreate, MemoryUpdate
from hippocampus.models.partition import Partition, PartitionCreate, PartitionUpdate


class MemoryStore(Protocol):
    """Abstract interface for memory persistence."""

    async def create(self, data: MemoryCreate, embedding: list[float] | None = None) -> Memory: ...
    async def get(self, memory_id: str) -> Memory | None: ...
    async def list(
        self,
        partition_id: str | None = None,
        tags: list[str] | None = None,
        offset: int = 0,
        limit: int = 50,
    ) -> tuple[list[Memory], int]: ...
    async def update(self, memory_id: str, data: MemoryUpdate) -> Memory | None: ...
    async def delete(self, memory_id: str) -> bool: ...
    async def search_by_vector(
        self,
        query_embedding: list[float],
        top_k: int = 10,
        partition_ids: list[str] | None = None,
    ) -> list[tuple[Memory, float]]: ...
    async def search_by_keyword(
        self,
        query: str,
        top_k: int = 10,
        partition_ids: list[str] | None = None,
    ) -> list[tuple[Memory, float]]: ...
    async def get_by_partition(self, partition_id: str) -> list[Memory]: ...
    async def delete_expired(self) -> list[str]: ...
    async def update_access(self, memory_id: str) -> None: ...
    async def update_embedding(self, memory_id: str, embedding: list[float]) -> None: ...
    async def update_expiry(self, memory_id: str, expires_at: str) -> None: ...


class PartitionStore(Protocol):
    """Abstract interface for partition persistence."""

    async def create(self, data: PartitionCreate, is_system: bool = False) -> Partition: ...
    async def get(self, partition_id: str) -> Partition | None: ...
    async def list(self) -> list[Partition]: ...
    async def update(self, partition_id: str, data: PartitionUpdate) -> Partition | None: ...
    async def delete(self, partition_id: str) -> bool: ...
    async def ensure_defaults(self) -> None: ...
