"""Abstract storage protocols."""

from __future__ import annotations

from typing import Protocol

from hebb.models.memory import Memory, MemoryCreate, MemoryUpdate
from hebb.models.partition import Partition, PartitionCreate, PartitionUpdate

# `list` is also the name of a method on the protocols below — once that
# method is defined, mypy resolves the unqualified `list` inside the
# class scope to the method (a Function) instead of the builtin. Alias
# at module scope so subsequent annotations stay unambiguous.
_List = list


class MemoryStore(Protocol):
    """Abstract interface for memory persistence."""

    async def create(self, data: MemoryCreate, embedding: _List[float] | None = None) -> Memory: ...
    async def get(self, memory_id: str) -> Memory | None: ...
    async def list(
        self,
        partition_id: str | None = None,
        tags: _List[str] | None = None,
        offset: int = 0,
        limit: int = 50,
    ) -> tuple[_List[Memory], int]: ...
    async def update(self, memory_id: str, data: MemoryUpdate) -> Memory | None: ...
    async def delete(self, memory_id: str) -> bool: ...
    async def search_by_vector(
        self,
        query_embedding: _List[float],
        top_k: int = 10,
        partition_ids: _List[str] | None = None,
    ) -> _List[tuple[Memory, float]]: ...
    async def search_by_keyword(
        self,
        query: str,
        top_k: int = 10,
        partition_ids: _List[str] | None = None,
    ) -> _List[tuple[Memory, float]]: ...
    async def corpus_size(self, partition_ids: _List[str] | None = None) -> int: ...
    async def keyword_doc_freqs(self, terms: _List[str], partition_ids: _List[str] | None = None) -> dict[str, int]: ...
    async def get_by_partition(self, partition_id: str) -> _List[Memory]: ...
    async def get_turn_neighbors(
        self,
        partition_id: str,
        session_id: str,
        turn_min: int,
        turn_max: int,
        exclude_ids: _List[str] | None = None,
    ) -> _List[Memory]: ...
    async def delete_expired(self) -> _List[str]: ...
    async def update_access(self, memory_id: str) -> None: ...
    async def update_embedding(self, memory_id: str, embedding: _List[float]) -> None: ...
    async def update_expiry(self, memory_id: str, expires_at: str) -> None: ...


class PartitionStore(Protocol):
    """Abstract interface for partition persistence."""

    async def create(self, data: PartitionCreate, is_system: bool = False) -> Partition: ...
    async def get(self, partition_id: str) -> Partition | None: ...
    async def list(self) -> _List[Partition]: ...
    async def update(self, partition_id: str, data: PartitionUpdate) -> Partition | None: ...
    async def delete(self, partition_id: str) -> bool: ...
    async def ensure_defaults(self) -> None: ...
